name: CD
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        run: |
          docker build -t app:latest .
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: '${{ secrets.REGISTRY_URL }}'
          username: '${{ secrets.REGISTRY_USER }}'
          password: '${{ secrets.REGISTRY_PASSWORD }}'

      - name: Push image to Container Registry
        run: |
          docker tag app:latest binhxikeno2/interview_nevel_tech:lastest
          docker push binhxikeno2/interview_nevel_tech:lastest
      - name: Send portainer webhook
        run: |
          curl --insecure --connect-timeout 60 -X POST ${{ secrets.PORTAINER_STACK_WEBHOOK }}
